language: node_js
node_js:
  - "10"
install:
  - sh install.sh
script:
  - sh build.sh
deploy:
  - provider: npm
    skip_cleanup: true
    api_key: ${NPM_TOKEN}
    email: ${NPM_USER}
    on:
      branch: master
      tags: false
  - provider: pages
    skip-cleanup: true
    github-token: ${GITHUB_TOKEN}
    local-dir: example/build/dist
    keep-history: true
    on:
      branch: master
      tags: false
